#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely
# Requirement: In between each iteration of the loop, add a sleep 2

while true
do
    echo "o infinity and beyond"
    sleep 2
done
